version: '3.7'
services:
  apinotify:
    build: .
    ports:
      - 3000:3000
    environment:
      - HOST=127.0.0.1
      - PORT=3000
      - MAX_RETRIES=5
      - RECONNECT_INTERVAL=10000
      - AUTHENTICATION_GLOBAL_AUTH_TOKEN=A4gx18YGxKAvR01ClcHpcR7TjZUNtwvE
      - APP_WEBHOOK_URL="https://webhook.site/dbf387ed-a861-4ae9-9b30-9344c972cb74"
      - APP_WEBHOOK_ALLOWED_EVENTS=MESSAGES_UPSERT,MESSAGES_DELETE,MESSAGES_UPDATE
      - APP_WEBHOOK_FILE_IN_BASE64=false